### ISSUE TITLE
Give this project a better name

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/kdb-boothroyd#55]
see: https://github.com/finos/kdb/issues/54#issuecomment-890981603

**Comment by OiNutter** [comment]
Some of my suggestions:

Pop culture references:
Boothroyd (Q from bond films, it's still my favourite even if it is niche)
Nellie (another bond reference)
Whitney (after inventor of Q language)
Suzie

Wordplay:
Qbit
Qball
Qb (cube)
OKDB

As you can see I'm a fan of the short single word pun or reference for naming software

**Comment by OiNutter** [comment]
Say hello to Boothroyd bbe5cd6792187cd2e29f7289ad8583ff0cfdab3f
