### ISSUE TITLE
Different query hotkeys to determine what text to submit to the server

### ISSUE THREAD

**Issue by gyorokpeter** [ScottLogic/kdb-boothroyd#63]
To aid with muscle memory of users used to KDB Studio, here is how the shortcuts work:

- Ctrl+Enter: send the line that the cursor is in (no matter what is selected)
- Ctrl+E with no selection: send the entire content of the editor window
- Ctrl+E with some text selected: send only the selected text, even if the selection doesn't start/end on a word boundary

When sending multiline text, it should use \n separators between the lines.

**Comment by ColinEberhardt** [comment]
Thanks @gyorokpeter - is there a complete list of keyboard shortcuts for the existing KDB Studio?

**Comment by gyorokpeter** [comment]
I think all of the important ones are actually shortcuts to menu which show you the shortcut when you open the menu.
