### ISSUE TITLE
dev console should not pop up in release build

### ISSUE THREAD

**Issue by gyorokpeter** [ScottLogic/kdb-boothroyd#65]
By this I'm referring to the exe file created by "npm run dist". Or if there is already an alternative command to achieve this, it should be documented in the readme.

**Comment by OiNutter** [comment]
How did you build the files before creating the exe? If you've previously just run `npm run dev:react` and `npm run dev:electron` then the app will be built for development not release. As mentioned in #66 the `npm run dist` command just packages the built files.

**Comment by gyorokpeter** [comment]
This is also not fixed by my attempt with "npm run build".

**Comment by OiNutter** [comment]
Did this get fixed by adding in `cross-env` to the commands for building a release?

**Comment by gyorokpeter** [comment]
Yes.
