### ISSUE TITLE
Buttons should not be needlessly hidden behind a "..." button

### ISSUE THREAD

**Issue by gyorokpeter** [ScottLogic/kdb-boothroyd#76]
There is no reason for these buttons not to be shown by default. Maybe if the toolbar becomes too crowded, the less important buttons might be hidden, but even KDB Studio didn't get that far.
![kép](https://user-images.githubusercontent.com/1097079/133934419-3bd12a23-274d-431d-b27a-f06a3b895757.png)

**Comment by ColinEberhardt** [comment]
Let's roll this into #75
