### ISSUE TITLE
Optimize windows build

### ISSUE THREAD

**Issue by gyorokpeter** [ScottLogic/kdb-boothroyd#91]
Apparently this step takes ages:
```
  • building        target=nsis-web file=dist\nsis-web\Boothroyd Web Setup 1.4.0.exe archs=x64 oneClick=false perMachine=false
```
By looking at process manager, this spawns two 7za.exe processes that use maxed CPU and even that way this step takes about 5 minutes.

Just having a separate build command that doesn't include this would also work as I'm not going to use that installer anyway.

**Comment by OiNutter** [comment]
We're using https://github.com/electron-userland/electron-builder to compile the app for the various platforms so we don't have much control over how they're doing the build stuff. I haven't played around with the nsis-web installer to see if it's worth keeping yet but I wanted to try it out as a way of giving users another option for installs. If you want to build without it you should be able to run `npm run dist -- -w nsis` to just build the nsis installer.

As our builds are happening in an automated pipeline speeding them up isn't a huge priority for us at this point.

**Comment by gyorokpeter** [comment]
What if I don't want to build either, and just run out of the win-unpacked directory?

**Comment by OiNutter** [comment]
You could try passing one of the options listed [here](https://www.electron.build/configuration/win) instead of `nsis`. I'd imagine `dir` might do what you want.
